version: '3'

services:
  morecats:
    build: .
    image: terracecn/morecats
    restart: always
    environment:
      HOST: 0.0.0.0
      CAT_IMAGE_DIR: /var/morecats/images
      CAT_IMAGE_SQLITE: /var/morecats/cat_images.db
    volumes:
      - ./data:/var/morecats
    ports:
      - 8080:8080
      